parameters:
    - name: dev
      type: string
      default: dev
    - name: test
      type: string
      default: test

variables:
- group: sample

stages:
    
  - stage: ${{ replace(parameters.repoName, '-', '_') }}
    jobs:
      - job: test_stage_name_transfer
        steps:
          - task: Bash@3
            displayName: Run bash
            inputs:
              targetType: Inline
              script: |
                printenv
