# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool: ubuntu-docker
#

variables:
#   repo1: "from var1"
#   branch1: "itssecond"
- template: dev-vars.yaml


stages:
- stage: dev_Stage 
  displayName: Dev Version
#   variables:
#     - template: test-vars.yaml
  - template: template/sample.yaml
# - template: template/sample.yaml

#steps:
#- task: NodeTool@0
#  inputs:
#    versionSpec: '10.x'
#  displayName: 'Install Node.js'
#
#- script: |
#    # npm install
#    # npm run build
#    printenv
#    echo "repo name: $(Build.Repository.Name)"
#    echo "source baranch name: $(Build.SourceBranchName)"
#    git_log=$(git log --merges origin/$(Build.SourceBranchName) --oneline --grep='^Merge pull request' -1)
#    echo "${git_log}"
#    echo "merged from: ${git_log##* }"
#    p_sb="${git_log##* }"
#    echo "p_sb: ${p_sb}"
#    oneaccount_prefix="aksharagyana/"
#    source_branch=${p_sb//$oneaccount_prefix/}
#    echo "source_branch: ${source_branch}"
#    echo "Build.SourcesDirectory $(Build.SourcesDirectory)"
#    ls -ltr $(Build.SourcesDirectory)
#    echo "current directory"
#    ls -ltr
#  displayName: 'print default vars'
