# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool: default
#

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    # npm install
    # npm run build
    printenv
    echo "repo name: $(Build.Repository.Name)"
    echo "source baranch name: $(Build.SourceBranchName)"
    sourcebranch=$(git log --merges origin/master --oneline --grep='^Merge pull request' -1)
    echo "${sourcebranch}"
    echo "merged from: ${sourcebranch##* }"
  displayName: 'print default vars'
