name: on-branch-delete

# Run this workflow every time a commit gets pushed to main or a pull request gets opened against main
on: [delete]

jobs:
  trigger-azure-pipelines:
    name: Call Azure Pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Azure Pipelines Action
        run: |
          getPayLoad() {
          cat <<EOF
          {
            "definition":  {
                       "id":  3
            },
            "templateParameters":
              {
                "repo": "${{ github.repository }}",
                "ref": "${{ github.event.ref }}",
                "type": "${{ github.event.ref_type }}"
              }
          }
          EOF
          }        
          curl -u gitaction:${{ secrets.AZURE_DEVOPS_TOKEN }} -H 'Content-Type: application/json' -X POST https://dev.azure.com/aksharagyana/node-pipeline/_apis/pipelines/3/runs?api-version=6.0-preview.1 --data "$(getPayLoad)"
#          echo "$response"
#        if [ "$response" == "" ]; then
#          echo "Integration tests triggered successfully"
#        else
#          exit 1
#        fi
#               bash ./esm-lib/.github/workflows/triggerAzPipeline.sh "${{ github.repository }}" "${{ github.event.ref }}" "${{ github.event.ref_type }}"

#        bash ./IntegrationTests/.github/workflows/TriggerIntegrationTests.sh ${{ secrets.L2_REPO_TOKEN }} ${{ github.event.pull_request.head.sha }} ${{ github.repository }} ${{ github.event.pull_request.number }} ${{ github.event.pull_request.head.ref }} ${{ github.event.pull_request.base.ref }}

#        uses: Azure/pipelines@v1
#        with:
#          azure-devops-project-url: https://dev.azure.com/aksharagyana/node-pipeline
#          azure-pipeline-name: 'aksharagyana.esm-lib'
#          azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
#          azure-pipeline-variables:  '{"repo": "${GITHUB_REPOSITORY}", "branch": "${GITHUB_REF_NAME}"}'