name: on-branch-delete

# Run this workflow every time a commit gets pushed to main or a pull request gets opened against main
on: [delete]

jobs:
  build:
    name: Call Azure Pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Azure Pipelines Action
        uses: Azure/pipelines@v1
        with:
          azure-devops-project-url: https://dev.azure.com/aksharagyana/node-pipeline
          azure-pipeline-name: 'aksharagyana.esm-lib'
          azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
          azure-pipeline-variables:  '{"repo": "${{ env. GITHUB_REPOSITORY }}", "branch": "${GITHUB_REF}"}'